- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  roles:
    - homebrew
    - { role: homebrew-cask, when: CI != "true" }
    - dotfiles
    - font
  environment:
    { HOMEBREW_NO_AUTO_UPDATE: 1, when: CI == "true" }
