- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  roles:
    - homebrew
    - dotfiles
    - { role: font, when: CI != "true" }
  environment:
    { HOMEBREW_NO_AUTO_UPDATE: 1, when: CI == "true" }
