---

- name: git clone my dotfiles
  git:
    repo=https://github.com/rhythnn/dotfiles.git
    dest=~/dotfiles
    version=master

- name: install powerline
  shell: pip3 install powerline-status

- name: mkdir vim dir
  file: path=~/.vim state=directory mode=0755

- name: mkdir nvim dir
  file: path=~/.config/nvim state=directory mode=0755

- name: create symlinks
  shell: sh ~/dotfiles/install.sh

- name: install emacs packages via cask
  shell: cask install
  args:
    chdir: ~/.emacs.d/

- name: install fisherman
  shell: curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisher

- name: install fish plugins via fisherman
  shell: fish ~/.config/fish/functions/fisher.fish
  args:
    chdir: ~/.config/fish/
