---

- name: git clone my dotfiles
  git:
    repo=https://github.com/rhythnn/dotfiles.git
    dest=~/dotfiles
    version=master

- name: git clone zplug
  git:
    repo=https://github.com/b4b4r07/zplug
    dest=~/.zplug
    version=master

- name: install oh-my-zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
  args:
    creates: ~/

- name: mkdir vim dir
  file: path=~/.vim state=directory mode=0755

- name: mkdir nvim dir
  file: path=~/.config/nvim state=directory mode=0755


- name: create dotfile symlinks
  file:
    src: ~/dotfiles/{{ item }}
    dest: ~/{{ item }}
    state: link
    force: yes

  with_items: "{{ dotfile_items }}"


- name: create symlinks of vim
  file:
    src: ~/dotfiles/vim/{{ item }}
    dest: ~/.vim/{{ item }}
    state: link
    force: yes

  with_items: "{{ vim_items }}"

- name: create symlinks of neovim
  file:
    src: ~/dotfiles/nvim/
    dest: ~/.config/nvim
    state: link
    force: yes

