---

- name: git clone my dotfiles
  git:
    repo=https://github.com/mataku/dotfiles.git
    dest=~/dotfiles
    version=master

- name: Install powerline
  shell: pip3 install powerline-status

- name: mkdir vim dir
  file: path=~/.vim state=directory mode=0755

- name: mkdir atom dir
  file: path=~/.atom state=directory mode=0755

- name: Create symlinks
  shell: ~/dotfiles/install.sh

- name: Install emacs packages via cask
  shell: cask install
  args:
    chdir: ~/.emacs.d/

- name: Install fisherman
  shell: curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisher

- name: Install fish plugins via fisherman
  shell: fish ~/.config/fish/functions/fisher.fish
  args:
    chdir: ~/.config/fish/

- name: Install atom packages
  shell: apm-beta install --packages-file ~/dotfiles/atom/packages.txt
  when: CI != "true"

- name: Create github.com dir
  file: path=~/github.com state=directory

- name: git clone robe dir
  git:
    repo=https://github.com/dgutov/robe
    dest=~/github.com/robe
    version=master
