---

- name: Tap Homebrew repositories
  homebrew_tap: tap={{ item }}
  with_items: "{{ homebrew_repositories }}"

- name: Install packages
  homebrew: name={{ item.name }} install_options={{ item.options | default() }}
  with_items: "{{ homebrew_packages }}"
