---

homebrew_repositories:
  - caskroom/cask
  - caskroom/versions
  - homebrew/dupes
  - homebrew/python
  - homebrew/science
  - homebrew/versions
  - neovim/neovim
  - sanemat/font
  - supermomonga/splhack

homebrew_packages:
  - { name: gcc }
  - { name: app-engine-python }
  - { name: fontforge }
  - { name: freetype }
  - { name: fontconfig }
  - { name: ghostscript }
  - { name: git, options: with-brewed-curl with-brewed-openssl}
  #- { name: gnuplot }
  - { name: go }
  - { name: grep }
  - { name: heroku-toolbelt }
  - { name: imagemagick }
  - { name: less }
  - { name: lua }
  - { name: mecab }
  - { name: mecab-ipadic }
  - { name: mysql }
  - { name: nkf }
  - { name: nodebrew }
  - { name: pandoc }
  - { name: peco }
  - { name: python3 }
  - { name: pypy3 }
  - { name: pyenv }
  - { name: neovim, options: HEAD }
  - { name: rbenv }
  - { name: readline }
  - { name: ricty, options: [powerline,vim-powerline] }
  - { name: ruby-build }
  - { name: ruby }
  - { name: source-highlight }
  - { name: tidy-html5 }
  - { name: tig }
  - { name: tree }
  - { name: vim, options: [with-lua,with-python3,override-system-vi]}
  - { name: zsh, options: without-etcdir }
  - { name: zsh-completions }

homebrew_cask_packages:
  - { name: android-studio }
  - { name: atom }
  # - { name: basictex }
  - { name: caffeine}
  - { name: github-desktop }
  - { name: google-chrome }
  - { name: google-japanese-ime }
  - { name: iterm2 }
  - { name: java }
  - { name: karabiner }
  - { name: otto }
  - { name: onyx}
  - { name: prott}
  - { name: skim }
  - { name: slack }
  - { name: visual-studio-code }
  - { name: xquartz }
